services:
  backend:
    build:
      context: ./backend
    container_name: sysml_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: bash launch.sh
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: sysml_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_APP_VERSION=${VITE_APP_VERSION}
    container_name: sysml_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000/api

  db:
    image: pgvector/pgvector:pg16
    container_name: sysml_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
