services:
  fastapi:
    container_name: fastapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/app:/app
    restart: unless-stopped
    env_file:
      - .env

  
