version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: sysml_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: bash launch.sh
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: sysml_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000/api

networks:
  default:
    driver: bridge


