"""Add internal_block_diagrams table for nested IBDs

Revision ID: add_internal_block_diagrams_table
Revises: 
Create Date: 2025-07-21 17:44:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_ibd_table'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_block_diagrams',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('parent_bdd_diagram_id', sa.Integer(), nullable=False),
        sa.Column('parent_block_id', sa.String(), nullable=False),
        sa.Column('nodes', sa.JSON(), nullable=False),
        sa.Column('edges', sa.JSON(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['parent_bdd_diagram_id'], ['diagram_embeddings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_block_diagrams_id'), 'internal_block_diagrams', ['id'], unique=False)
    op.create_index(op.f('ix_internal_block_diagrams_parent_block_id'), 'internal_block_diagrams', ['parent_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_block_diagrams_parent_block_id'), table_name='internal_block_diagrams')
    op.drop_index(op.f('ix_internal_block_diagrams_id'), table_name='internal_block_diagrams')
    op.drop_table('internal_block_diagrams')
    # ### end Alembic commands ###